name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./API/API.csproj
      run: dotnet restore ./APItests/APITests.csproj
    - name: Build
      run: dotnet build ./API/API.csproj --no-restore
      run: dotnet build ./APItests/APITests.csproj --no-restore
    - name: Test
      run: dotnet test ./API/API.csproj --no-build --verbosity normal
      run: dotnet test ./APItests/APITests.csproj --no-build --verbosity normal